### ISSUE TITLE
Feature Request: accept list of files from STDIN

### ISSUE THREAD

**Issue by defaultxr** [tavianator/bfs#10]
One thing I've always thought would be great as a part of 'find' is accepting a list of files on stdin instead of searching through a provided directory. That way you could use the filters of find/bfs just on a list of files.

i.e.

$ cat foo
/home/user/file.txt
/home/user/file2.txt
/home/user/blah/file99.mp3
$ cat foo | bfs - -ctime +1
/home/user/file.txt
$ cat foo | bfs - -name '*.mp3'
/home/user/blah/file99.mp3

This sort of thing could probably also be done by using a bunch of other commands and parsing their output with grep. But it would be a lot more convenient and would significantly reduce cognitive load to be able to just pipe a list of files into bfs and use its filters on them.

I think this would be a great enhancement for bfs and would be yet another reason to use it over find. Either way, bfs is great and I'm thankful for your work on it!

**Comment by tavianator** [comment]
I've seen a similar feature request on the `bug-findutils` list: https://lists.gnu.org/archive/html/bug-findutils/2016-02/msg00005.html.

Strictly speaking POSIX says that `find -` has to look for a file/directory named `-`, so that syntax won't work as-is.  I'm definitely considering adding `-f PATH` support, and at the same time something like `-files-from PATH` could also be added.

For now of course you can do `bfs $(cat foo) -name ...` unless `foo` contains files with spaces or that look like options.

**Comment by tavianator** [comment]
I'm not likely to implement this any time soon, as it's possible to do this with an external script and I personally wouldn't use it often.  But thanks for the suggestion!
