### ISSUE TITLE
POSIXLY_CORRECT: activate if argv[0] is `find`

### ISSUE THREAD

**Issue by yoshiyoshyosh** [tavianator/bfs#122]
while `bfs` is already compatible with POSIX `find` by default, having extra reassurance by enabling `posixly_correct` if `argv[0]` is `find` just in case anything changes would be nice

this request stems from [adding `bfs` to void linux's `find` alternatives group](https://github.com/void-linux/void-packages/pull/45607)

**Comment by tavianator** [comment]
First of all, thanks for suggesting this to Void LInux.  I have run `bfs` as my system `find` implementation as well on and off for years, and it seems to work fine.  So having that configuration be easily supported is nice.  (It's awkward on Arch Linux because you still need GNU `xargs`, but the `findutils` package is not spit.)

In terms of this issue, I'm not convinced that activating `POSIXLY_CORRECT` is the right thing to do just because `argv[0]` is `find`.  Currently, `bfs` behaves exactly like GNU `find` regarding that environment variable.  I don't think it's worth trying to be "more" POSIX-compliant than GNU find by default.  Note that the only effects of `POSIXLY_CORRECT` are:

- `POSIXLY_CORRECT` disables warnings by default.  This is due to a POSIX rule that if anything is printed to stderr, the exit status must be nonzero.

- `POSIXLY_CORRECT` switches from 1024-byte to 512-byte blocks for `-ls`.  GNU `find` does this too, even though `-ls` is not specified by POSIX.  See #77.

**Comment by tavianator** [comment]
> perhaps slightly more clear documentation about it (really just a mention of it following how GNU does it in the man page) would be helpful.

Done in d49e44a5e55d834a609753b113d6055a056c4091!
