### ISSUE TITLE
Does not build on hurd-i386

### ISSUE THREAD

**Issue by lamby** [tavianator/bfs#24]
Via https://bugs.debian.org/861569:

```
  mtab.c:23:24: fatal error: sys/mount.h: No such file or directory
   # include <sys/mount.h>
```

You can see a full build log here: https://buildd.debian.org/status/fetch.php?pkg=bfs&arch=hurd-i386&ver=1.0-2&stamp=1493474679&raw=0

(See my comments on the above bug report, re. Linuxisms)

**Comment by tavianator** [comment]
Actually the issue is not enough Linux-isms :)

Specifically, that include is guarded by `#elif BSD`, but that seems to be true on Hurd.  The codepath it should be using is guarded by `#if __linux__`, but I guess it should really be something like `#if __GLIBC__`.

With that change, `bfs` builds, but 7 test cases fail.

**Comment by tavianator** [comment]
Commits facf34b..72685e2 fix all the bugs I ran into building on Hurd.  Let me know if you run into any other issues.

**Comment by lamby** [comment]
Appears to build fine now - many thanks :)
