### ISSUE TITLE
Make -nohidden position independent

### ISSUE THREAD

**Issue by kaushalmodi** [tavianator/bfs#30]
Hello,

When I do:

```
bfs -nohidden . -name "*foo*"
```

it works great! Fast, and ignoring dirs starting with `.`, as expected.

But when I do:

```
bfs . -name "*foo*" -nohidden
```

the `-nohidden` switch is not effective.. I get search results from hidden dirs too (dirs starting with `.`)!

**Comment by tavianator** [comment]
That command line is equivalent to `bfs -name '*foo*' -and -nohidden`, and since `-and` is short-circuiting, `-nohidden` doesn't even get a chance to run if `-name '*foo'` returns false.  So it will filter out any hidden files/directories that match `*foo*` but no other ones.  I agree that this is confusing, and I'm open to suggestions of better semantics for it.

**Comment by kaushalmodi** [comment]
> I agree that this is confusing, and I'm open to suggestions of better semantics for it.

I don't code in C. So I wish I could have provided some useful suggestions. Dumb thought: Is it possible to treat `-nohidden` as a special switch, and not AND it with the rest?

**Comment by tavianator** [comment]
That would be possible yeah, I'll try it out and see how nice it is in practice.

Related to #8.
