### ISSUE TITLE
statx redefinition error

### ISSUE THREAD

**Issue by Earnestly** [tavianator/bfs#35]
glibc has [recently added `statx`](https://sourceware.org/git/?p=glibc.git;a=commit;h=fd70af45528d59a00eb3190ef6706cb299488fcd) which results in following redefinition error:

```
cc -D__EXTENSIONS__ -D_ATFILE_SOURCE -D_BSD_SOURCE -D_DARWIN_C_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DBFS_VERSION=\"1.2.2-10-g9caf477\" -D_FORTIFY_SOURCE=2 -std=c99 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -MD -MP -MF typo.d -c typo.c -o typo.o
In file included from stat.c:27:
/usr/include/linux/stat.h:56:8: error: redefinition of 'struct statx_timestamp'
 struct statx_timestamp {
        ^~~~~~~~~~~~~~~
In file included from /usr/include/sys/stat.h:446,
                 from stat.c:23:
/usr/include/bits/statx.h:25:8: note: originally defined here
 struct statx_timestamp
        ^~~~~~~~~~~~~~~
In file included from stat.c:27:
/usr/include/linux/stat.h:99:8: error: redefinition of 'struct statx'
 struct statx {
        ^~~~~
In file included from /usr/include/sys/stat.h:446,
                 from stat.c:23:
/usr/include/bits/statx.h:36:8: note: originally defined here
 struct statx
        ^~~~~
make: *** [Makefile;64: stat.o] Error 1
make: *** Waiting for unfinished jobs....
```

Pulseaudio had a similar situation when glibc added `memfd`, here is their solution: https://github.com/pulseaudio/pulseaudio/commit/dfb0460fb4743aec047cdf755a660a9ac2d0f3fb#diff-a3824a947f7132abd61ce6a8a9b5e2a4

You could possibly check if `__NR_statx` defined, but I'm not sure.

Alternatively it might be better to expose a `-D` flag via the `Makefile` and guard against that in the implementation.  That way I can compile it with `make HAVE_STATX=1` or something like it.

**Comment by tavianator** [comment]
Ah finally!  Thanks for the heads up.

> You could possibly check if `__NR_statx` defined, but I'm not sure.

It already checks that actually, to see if the syscall is available for the current arch.

The issue is that glibc now declares its own versions of the kernel types, which conflict with the names of the `linux/stat.h` ones.  So if glibc has statx() support, we have to avoid including the kernel headers.  I have a patch that does this, just need to test it against a new glibc with the wrapper.

I see the new glibc wrapper doesn't cache the `ENOSYS`, so there may be a performance regression on systems with new glibc and older kernels.  I expect such configurations are rare though.
