### ISSUE TITLE
Deleting empty folders recursively, skipping hidden directories

### ISSUE THREAD

**Issue by chapmanjacobd** [tavianator/bfs#92]
I've been using this for a while and it works well

```
bfs -type d -exec bfs -f {} -not -type d -exit 1 \; -prune -ok bfs -f {} -type d -delete \;
```

How do I skip top-level hidden folders? I tried this

```
bfs -nohidden -type d -exec bfs -nohidden -f {} -not -type d -exit 1 \; -prune -ok bfs -nohidden -f {} -type d -delete \;
```

but it seems to match more folders

```
bfs: error: ./some/folder: Directory not empty.
```

**Comment by tavianator** [comment]
I think you have too many `-nohidden`s :)

- The first one causes the outer `bfs` to skip hidden files, so they won't be checked for emptiness or deleted.  I think this is what you want.
- The second one causes `bfs` to ignore hidden files when checking if a directory is empty.  Maybe this is also what you want?
- The third one causes `bfs` to ignore hidden files when deleting.  This is probably not what you want, since if you don't delete a hidden file, you can't delete its parent either, etc.

**Comment by chapmanjacobd** [comment]
yes you are right. The `bfs -nohidden -type d -exec bfs -f {} -not -type d -exit 1 \; -prune -ok bfs -f {} -type d -delete \;` incantation seems to be the desired behavior

**Comment by tavianator** [comment]
Circling back to this, I actually had the same desire to delete "recursively empty" directories the other day, and it occurred to me that the following simpler invocation works:

```console
tavianator@graphene $ bfs -type d -empty -delete
```

This works because `-delete` turns on post-order traversal (aka `-depth`), so it will start with leaf directories and work upwards.  At each level, `-empty` is testing the directory *after* we've already deleted its empty children.

For your use case, I believe just adding `-nohidden` does the right thing, but I didn't think too carefully about it.  Here's an example though:

```console
tavianator@graphene $ tree -a
.
├── empty
├── full
│   └── file
├── .hidden
│   └── empty
└── recursively
    └── empty

7 directories, 1 file
tavianator@graphene $ bfs -nohidden -type d -empty -delete
tavianator@graphene $ tree -a
.
├── full
│   └── file
└── .hidden
    └── empty

4 directories, 1 file
```

You do lose the `-ok` confirmation this way.  You could do

```console
tavianator@graphene $ bfs -depth -nohidden -type d -empty -ok rmdir {} \;
rmdir ./empty ? y
rmdir ./recursively/empty ? y
rmdir ./recursively ? y
```

But that prompts on *every* deleted directory, not just the top-level ones.
